[management_servers]
management ansible_host=13.232.201.231

[jenkins_servers]
jenkins ansible_host=52.66.202.36

[control_plane_servers]
control-plane ansible_host=13.207.193.204

[workers]
worker1 ansible_host=13.127.177.31
worker2 ansible_host=3.110.187.222

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/padig/.ssh/devops-key.pem